internal/common/objects/BaseBiker.go
internal/common/objects/LootBox.go
internal/common/objects/MegaBike.go
internal/common/physics/engine.go
internal/common/utils/CommonFunctions.go
internal/common/utils/CommonParameters.go
internal/common/utils/CommonTypes.go

Myself and @mercykid have created engine and megabike structs

Added MegaBike and Engine Structs

---

internal/common/objects/BaseBiker.go

Add BikerAction enum as return type of DecideAction

---

internal/common/objects/BaseBiker.go
internal/common/objects/LootBox.go
internal/common/utils/CommonFunctions.go
internal/server/GameLoop.go

-  lootbox was made a physics object to simplify the interface and use the checkForCollision() function
-  grouped the resourceAllocationParameters into a struct to simplify the baseBiker interface and to allow for easy future changes to the parameters 
- simplified the lootbox sharing function while we wait on a decision on how to implement different sharing protocols/ what parameters we want to take into account while distributing loot

simplified basebiker interface and loot distribution function

---

internal/common/objects/Audi.go
internal/common/objects/BaseBiker.go
internal/common/objects/LootBox.go
internal/common/objects/MegaBike.go
internal/common/objects/PhysicsObject.go
internal/common/physics/engine.go
internal/common/utils/CommonParameters.go
internal/common/utils/CommonTypes.go
internal/server/GameLoop.go

Decoupled Engine from Server and IPhysicsObject. 
PLEASE ACCEPT THIS PR BEFORE MERGING HARRY/GAME-LOOP

Engine update

---

internal/common/objects/BaseBiker.go

Due to how inheritance in golang we cannot edit member variables when we inherit the struct. For example, inheriting basebiker does not mean you can modify bb.forces. Therefore i have created a setter for this instead.

Added setter for forces for base biker

---

internal/common/objects/BaseBiker.go

added property 'reputation' and defined three function might be used in the future

add property 'reputation' into BaseBiker

---

internal/common/physics/engine.go

origin ComputeOrientation didnt return correct value

fix ComputeOrientation in phy-engine

---

internal/common/voting/VotingMethods.go

fix the logic of each function with weight of different agents

finish the logic of functions with weight of different agents

---

internal/common/utils/CommonParameters.go
internal/common/voting/VotingEngine.go
internal/server/GameLoop.go
internal/server/Governance.go

fix the error of changing input parameter to a mapmap and a map
also, add two TODO in the project

fix the error of voting Methods with mapmap and map input

---

visualiser/entities/Agents.py

Remove resource alloc parameters to make visualiser work with iteration2

Update visualiser to work with iteration2

---

internal/server/Server.go
internal/server/tests/audi_test.go
internal/server/tests/game_loop_test.go
internal/server/tests/game_state_test.go
internal/server/tests/governance_test.go

Got all tests to work with current iteration2 branch.

Test Fixes and TestRunActionProcess improvement

---

internal/server/Server.go
internal/server/SimLoop.go
internal/server/tests/sim_loop_test.go

Added tests for simulation loop functions
Fixed  some problems with reset game state

Sim loop test

---

.gitignore
Visualiser.py
visualiser/GameScreen.py
visualiser/entities/Awdi.py
visualiser/entities/Bikes.py
visualiser/entities/Common.py
visualiser/entities/Lootboxes.py
visualiser/util/Constants.py

- Add mac fix
- Add console
- Add some metrics
- Fix coordinate system
- Fix overlay drawing order

Visualiser iteration2

---

internal/common/objects/Audi.go
internal/common/objects/BaseBiker.go
internal/common/objects/MessageTypes.go
internal/server/GameStateDump_Banned.go

Added message types for what agents voted for

Added messaging for votes

---

internal/clients/team5/BikerElections.go
internal/clients/team5/CumulativeLootPreferences.go
internal/clients/team5/LootAlloc.go
internal/clients/team5/Pedal_And_Steer.go
internal/clients/team5/Reputation.go
internal/clients/team5/message.go
internal/clients/team5/stateMachine.go
internal/clients/team5/team5.go

Team 5 NaN fix

---

internal/clients/team4/README.md
internal/clients/team4/allocation.go
internal/clients/team4/baseline.go
internal/clients/team4/data.go
internal/clients/team4/decision.go
internal/clients/team4/direction.go
internal/clients/team4/messaging.go
internal/clients/team4/opinion.go
internal/server/Spawner.go

try again, really sorry and i'm confused

add team4 folder

---

internal/common/objects/MegaBike.go
internal/common/objects/tests/megabikes_test.go

Added fix for excess steering forces to wrap around

---

internal/clients/team2/modules/ForceVector.go
internal/server/Spawner.go

team 2: fix NaN

---

internal/clients/team2/modules/Environment.go

team 2: fix nil lootbox

---

internal/clients/team7/agents/TeamSevenBiker.go
internal/clients/team7/frameworks/NavigationDecisionFramework.go
internal/clients/team7/frameworks/SocialNetwork.go
internal/clients/team7/frameworks/VoteToKick.go
internal/server/Spawner.go
internal/server/tests/Experiment_Average.py

Fix to Team 7 and adjustment of Weights

Fix to Team 7 and adjustment of Weights

---

internal/clients/team7/agents/TeamSevenBiker.go
internal/clients/team7/frameworks/BikeDecisionFramework.go
internal/clients/team7/frameworks/EnvironmentHandler.go
internal/clients/team7/frameworks/NavigationDecisionFramework.go
internal/clients/team7/frameworks/OpinionFramework.go
internal/clients/team7/frameworks/Personality.go
internal/clients/team7/frameworks/SocialNetwork.go
internal/clients/team7/frameworks/VoteAllocation.go
internal/clients/team7/frameworks/VoteDictator.go
internal/clients/team7/frameworks/VoteGovernance.go
internal/clients/team7/frameworks/VoteLeader.go
internal/clients/team7/frameworks/VoteProposals.go
internal/clients/team7/frameworks/VoteToAccept.go
internal/clients/team7/frameworks/VoteToKick.go
internal/clients/team7/frameworks/VotingFramework.go

Added comments to clarify purpose of each file for Team 7's agent. Please feel free to add/suggest extra comments of your own where you see fit.

Added comments to Team 7 agent.
